#!/usr/bin/env bash

NTCF_TESTVOCABULARY_EXE=${0}
NTCF_TESTVOCABULARY_DIRECTORY=$(dirname ${NTCF_TESTVOCABULARY_EXE})
if [[ -n ${NTCF_TESTVOCABULARY_DIRECTORY##/*} ]]; then
    NTCF_TESTVOCABULARY_DIRECTORY=$PWD/${NTCF_TESTVOCABULARY_DIRECTORY#.}
fi

cd ${NTCF_TESTVOCABULARY_DIRECTORY}

ntf generate -v 0 --debug -I ${NTCF_TESTVOCABULARY_DIRECTORY} ${NTCF_TESTVOCABULARY_DIRECTORY}/ntcf_testvocabulary.idl
